version: '2'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/services.d:/etc/nginx/services.d:ro
      - ./nginx/snake-oil-server.crt:/etc/nginx/server.crt:ro
      - ./nginx/snake-oil-server.key:/etc/nginx/server.key:ro
      - ./gene.iobio:/usr/share/nginx/gene.iobio:ro
      - ./data-vol/local_cache:/usr/share/nginx/local_cache:ro
      - /mnt/gene-data:/usr/share/nginx/data:ro
    depends_on:
      - geneinfo
      - gene2pheno
      - hpo
      - coverage
      - od_samtools
      - samtools
      - bcftools
      - freebayes
      - vcflib
      - vt
      - od_tabix
      - tabix
      - vcfdepther
      - af
      - vep
      - phenolyzer
      - email

  geneinfo:
    image: qiaoy/iobio.geneinfo:v1.0
    volumes:
      - ./data-vol/geneinfo:/home/iobio/workdir/geneinfo:ro
  gene2pheno:
    image: qiaoy/iobio.gene2pheno:v1.0
    volumes:
      - ./data-vol/gene2pheno:/home/iobio/workdir/gene2pheno:ro
  hpo:
    image: qiaoy/iobio.hpo:v1.0
    volumes:
      - ./data-vol/hpo:/home/iobio/workdir/hpo:ro
  coverage:
    image: qiaoy/iobio.coverage:v2.3
  od_samtools:
    image: qiaoy/iobio.samtools_od:v2.3
  samtools:
    image: qiaoy/iobio.samtools:v2.3
  bcftools:
    image: qiaoy/iobio.bcftools:v2.3
  freebayes:
    image: qiaoy/iobio.freebayes:v2.3
    volumes:
      - ./data-vol/data:/home/iobio/workdir/data:ro
  vcflib:
    image: qiaoy/iobio.vcflib:v2.3
  vt:
    image: qiaoy/iobio.vt:v2.3
    volumes:
      - ./data-vol/data:/home/iobio/workdir/data:ro
  od_tabix:
    image: qiaoy/iobio.tabix_od:v2.3
  tabix:
    image: qiaoy/iobio.tabix:v2.3
  vcfdepther:
    image: qiaoy/iobio.vcfdepther:v2.3
  af:
    image: qiaoy/iobio.af:v2.3
    volumes:
      - ./data-vol/afdata:/home/iobio/workdir/afdata:ro
  vep:
    image: qiaoy/iobio.vep:v2.3
    volumes:
      - ./data-vol/vep-cache:/home/iobio/workdir/vep-cache:ro
  phenolyzer:
    image: qiaoy/iobio.phenolyzer
  email:
    image: qiaoy/iobio.email-server
    volumes:
      - ./emailServer.ini:/home/iobio/workdir/emailServer.ini:ro
