#/bin/bash 
docker pull nginx:stable-alpine
docker pull qiaoy/iobio.geneinfo:v2.3.1
docker pull qiaoy/iobio.gene2pheno:v1.0
docker pull qiaoy/iobio.genecoverage:v2.3
docker pull qiaoy/iobio.genomebuild:v2.3
docker pull qiaoy/iobio.hpo:v1.0
docker pull qiaoy/iobio.coverage:v2.3
docker pull qiaoy/iobio.samtools:v2.3
docker pull qiaoy/iobio.samtools_od:v2.3
docker pull qiaoy/iobio.bcftools:v2.3
docker pull qiaoy/iobio.freebayes:v2.3
docker pull qiaoy/iobio.knownvariants:v2.3
docker pull qiaoy/iobio.vcflib:v2.3
docker pull qiaoy/iobio.vt:v2.3
docker pull qiaoy/iobio.tabix:v2.3
docker pull qiaoy/iobio.tabix_od:v2.3
docker pull qiaoy/iobio.vcfdepther:v2.3
docker pull qiaoy/iobio.af:v2.3.1
docker pull qiaoy/iobio.vep:v2.3.1
docker pull qiaoy/iobio.phenolyzer:v2.3
docker pull qiaoy/iobio.email-server
